package:
    name: presto
    version: {{ GIT_DESCRIBE_TAG | replace("v","") }}

source:
    path: ../presto
    patches:
        - compilers.patch

build:
    number: {{ GIT_DESCRIBE_NUMBER }}

test:
    imports:
        - presto

requirements:
    build:
        - {{ compiler('c') }}
        - {{ compiler('fortran') }}
    host:
        - cfitsio
        - pgplot
        - fftw
        - glib
        - python {{ python }}
        - pip
        - numpy
        - scipy
        - astropy
    run:
        - cfitsio
        - pgplot
        - fftw
        - glib
        - python
        - future
        - numpy
        - scipy
        - astropy
        - tempo
